using System.Text.Json;
using System.Text.RegularExpressions;
using System.Windows;
namespace DomainConsole;
public sealed partial class RemoteService {
 public static string ReportQueueScript=>DeliveryScripts.Client[..DeliveryScripts.Client.IndexOf("$probe|ConvertTo-Json",StringComparison.Ordinal)]+"\n$probe.Services=(@(Get-Service wuauserv,bits,cryptsvc,UsoSvc -ErrorAction Stop|ForEach-Object {$_.Name+': '+$_.Status}) -join '; ');$probe|ConvertTo-Json -Depth 5 -Compress";
 public async Task<ClientReportProbe> ReadReportQueue(TargetRecord target){using var timeout=new CancellationTokenSource(TimeSpan.FromSeconds(45));return JsonSerializer.Deserialize<ClientReportProbe>(await PowerShellBridge.Execute(Invoke(target.Host,ReportQueueScript),timeout.Token),Store.Options)??throw new Exception("Не получены данные очереди.");}
}
public partial class MainWindow {
 readonly Dictionary<string,DateTimeOffset> automaticReportChecks=new(StringComparer.OrdinalIgnoreCase);
 int ReportAgeHours()=>Store.Read("report-age-hours.json",24);
 void SaveReportAge_Click(object sender,RoutedEventArgs e)=>Guard(()=>{if(!int.TryParse(ReportAgeBox.Text,out var hours)||hours<1||hours>720)throw new Exception("Возраст отчёта: 1–720 часов.");Store.Write("report-age-hours.json",hours);Notify("Порог диагностики отчётности сохранён.");});
 public static string QueueAdvice(ClientReportProbe client,int hours,DateTimeOffset now){if(client.QueueError.Length>0||client.Queues.Count<2)return "Очередь прочитана не полностью. Очистка не рекомендуется без дополнительной диагностики. "+client.QueueError;var old=client.Queues.Any(q=>q.Files>0&&DateTimeOffset.TryParse(q.OldestUtc,out var at)&&now-at>=TimeSpan.FromHours(hours));return old?"Старый отчёт и накопившиеся события: рекомендуется «Восстановить отчётность» после завершения обновлений. Действие запускается вручную.":client.Queues.All(q=>q.Files==0)?"Очередь пуста. Очистка не требуется; предложена расширенная «Диагностика отчёта».":"Есть новые события, но длительное накопление не подтверждено. Не очищайте очередь; проверьте доставку отчёта.";}
 async Task CheckOldReport(ComputerRow row,WsusReport report){if(!DateTimeOffset.TryParse(report.LastReportedUtc,out var last)||DateTimeOffset.UtcNow-last>=TimeSpan.FromHours(ReportAgeHours())){if(automaticReportChecks.TryGetValue(row.Host,out var previous)&&DateTimeOffset.UtcNow-previous<TimeSpan.FromMinutes(10))return;automaticReportChecks[row.Host]=DateTimeOffset.UtcNow;string text;try{var client=await remote.ReadReportQueue(row.Target);text="## Автоматическая диагностика устаревшего отчёта\nСнимок: "+DateTimeOffset.Now.ToString("dd.MM.yyyy HH:mm:ss")+"\n"+QueueAdvice(client,ReportAgeHours(),DateTimeOffset.UtcNow)+"\n"+string.Join("; ",client.Queues.Select(q=>q.Name+": "+q.Files+" файлов, "+q.Bytes+" байт"))+"\nWUServer: "+client.WUServer+"; WUStatusServer: "+client.WUStatusServer+"; UseWUServer: "+client.UseWUServer+"\nСлужбы: "+client.Services+"\nЭто лёгкая проверка очереди, политик и служб; HTTP отдельно проверяется расширенной диагностикой.";}catch(Exception ex){text="## Автоматическая диагностика отчётности\nДанные клиента недоступны: "+ex.Message+"\nПричина не установлена; восстановление автоматически не запускается.";}var key=ExecutionRow(row,true).JobId+row.Host;deliveryReports[key]=text;Store.Write("delivery-reports.json",deliveryReports);if(IsCurrent(row))ShowCurrent();}else{var key=ExecutionRow(row,true).JobId+row.Host;if(deliveryReports.TryGetValue(key,out var text)&&text.StartsWith("## Автоматическая")){deliveryReports.Remove(key);Store.Write("delivery-reports.json",deliveryReports);if(IsCurrent(row))ShowCurrent();}}}
}
