using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using DomainConsole.Shared;
namespace DomainConsole;
public sealed class HistoryDetails:Window {
 public string ActionName {get;private set;}="";public List<TextBox> Editors {get;}=new();readonly RemoteJob job;
 public HistoryDetails(Window owner,RemoteJob source){job=source;Owner=owner;Title="Команды и параметры задания";Width=820;Height=700;MinWidth=620;MinHeight=420;WindowStartupLocation=WindowStartupLocation.CenterOwner;Background=new SolidColorBrush(Color.FromRgb(244,247,251));var dock=new DockPanel{Margin=new(16)};var title=new TextBlock{Text=source.Name+"\n"+new LocalDateConverter().Convert(source.Created,typeof(string),"Short",System.Globalization.CultureInfo.InvariantCulture)+" · ПК: "+source.Targets.Count,FontWeight=FontWeights.SemiBold,Margin=new(0,0,0,10),TextWrapping=TextWrapping.Wrap};DockPanel.SetDock(title,Dock.Top);dock.Children.Add(title);
 var actions=new WrapPanel{Margin=new(0,10,0,0)};void Button(string text,string action){var b=new Button{Content=text,Margin=new(0,0,6,0),Padding=new(10,7,10,7)};b.Click+=(s,e)=>{if(action=="Copy"){Clipboard.SetText(string.Join("\n\n",source.Steps.Select((step,i)=>Editors[i].IsReadOnly?Describe(step):Editors[i].Text)));return;}ActionName=action;DialogResult=true;};actions.Children.Add(b);}Button("Копировать команды","Copy");Button("Результаты","Results");Button("Повторить исходные","Repeat");Button("В редактор для нового запуска","Edit");DockPanel.SetDock(actions,Dock.Bottom);dock.Children.Add(actions);
 var panel=new StackPanel();panel.Children.Add(new TextBlock{Text="Правки не изменяют историю. Перед запуском нового задания проверьте цели и параметры.",TextWrapping=TextWrapping.Wrap,Foreground=Brushes.SlateGray,Margin=new(0,0,0,10)});panel.Children.Add(new TextBlock{Text="Microsoft для восстановления: "+source.MicrosoftSource+"; автоперезагрузка: "+source.AutoReboot+"; продолжать после ошибки: "+source.ContinueOnError,TextWrapping=TextWrapping.Wrap,Margin=new(0,0,0,10)});
 for(int i=0;i<source.Steps.Count;i++){var step=source.Steps[i];panel.Children.Add(new TextBlock{Text=(i+1)+". "+step.Name+" · "+step.Kind,FontWeight=FontWeights.SemiBold,Margin=new(0,8,0,4)});bool editable=step.Kind is "CMD" or "PowerShell";var box=new TextBox{Text=editable?step.Code:Describe(step),IsReadOnly=!editable,AcceptsReturn=true,AcceptsTab=true,TextWrapping=TextWrapping.Wrap,FontFamily=new FontFamily("Consolas"),MinHeight=80,MaxHeight=240,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};Editors.Add(box);panel.Children.Add(box);}
 var tech=new Expander{Header="Компьютеры и технические данные",Margin=new(0,12,0,0),Content=new TextBox{IsReadOnly=true,Text="ID: "+source.Id+"\n"+string.Join("\n",source.Targets.Select(t=>t.Host+" · "+ComputerRow.StatusText(t.Status))),TextWrapping=TextWrapping.Wrap,AcceptsReturn=true}};panel.Children.Add(tech);dock.Children.Add(new ScrollViewer{Content=panel,VerticalScrollBarVisibility=ScrollBarVisibility.Auto});Content=dock;}
 public List<CommandStep> EditedSteps()=>job.Steps.Select((step,i)=>new CommandStep{Name=step.Name,Kind=step.Kind,Code=Editors[i].IsReadOnly?step.Code:Editors[i].Text}).ToList();
 static string Describe(CommandStep step)=>string.IsNullOrWhiteSpace(step.Code)?"Встроенная операция: "+step.Name+". Параметры показаны выше.":step.Code;
}
public partial class MainWindow {
 async void HistoryDetails_Click(object sender,RoutedEventArgs e)=>await Guard(async()=>{if(HistoryGrid.SelectedItem is not RemoteJob job)throw new Exception("Выберите задание.");var dialog=new HistoryDetails(this,job);if(dialog.ShowDialog()!=true)return;if(dialog.ActionName=="Results"){OpenJob(job,true);return;}if(dialog.ActionName=="Repeat"){OpenJob(job,false);MicrosoftBox.IsChecked=job.MicrosoftSource;RebootBox.IsChecked=job.AutoReboot;ContinueBox.IsChecked=job.ContinueOnError;await Submit(Store.Clone(job.Steps),IsWsusJob(job)?"WSUS":"Commands");return;}var steps=dialog.EditedSteps();Steps.Clear();foreach(var step in steps)Steps.Add(step);if(steps.Count>0){Editor.Text=steps[0].Code;KindBox.SelectedIndex=steps[0].Kind=="PowerShell"?1:0;}MicrosoftBox.IsChecked=job.MicrosoftSource;RebootBox.IsChecked=job.AutoReboot;ContinueBox.IsChecked=job.ContinueOnError;CommandOptions.IsExpanded=true;MainTabs.SelectedItem=CommandsTab;Notify("Подготовлен новый набор. Исходная история сохранена; запуск — «Выполнить набор шагов».");});
 void HistoryDetails_DoubleClick(object sender,System.Windows.Input.MouseButtonEventArgs e){if(HistoryGrid.SelectedItem!=null)HistoryDetails_Click(sender,new RoutedEventArgs());}
}
