using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Documents;
using System.Text.RegularExpressions;
using DomainConsole.Shared;
namespace DomainConsole;
public sealed class LogViewer:UserControl {
 public static readonly DependencyProperty TextProperty=DependencyProperty.Register(nameof(Text),typeof(string),typeof(LogViewer),new PropertyMetadata("",(d,e)=>((LogViewer)d).Render()));
 public string Text {get=>(string)GetValue(TextProperty);set=>SetValue(TextProperty,value);}
 readonly StackPanel groups=new();readonly ScrollViewer scroll=new(){VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};
 readonly TextBox search=new(){MinWidth=70,ToolTip="Найти текст в отображаемых группах журнала."};readonly ComboBox filter=new(){Width=115};
 public bool AutoScroll {get;set;}
 public event EventHandler? CopyRequested;public event EventHandler? DownloadRequested;public event EventHandler? RefreshRequested;
 readonly Dictionary<string,bool> expanded=new();
 public LogViewer(){var dock=new DockPanel();var tools=new Grid{Margin=new(0,0,0,6)};tools.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});tools.ColumnDefinitions.Add(new(){Width=GridLength.Auto});tools.ColumnDefinitions.Add(new(){Width=GridLength.Auto});search.Margin=new(0,0,6,0);search.ToolTip="Поиск по тексту журнала";var searchField=new Grid();searchField.Children.Add(search);var hint=new TextBlock{Text="Поиск в журнале",Margin=new(6,6,0,0),Foreground=Brushes.SlateGray,IsHitTestVisible=false};searchField.Children.Add(hint);search.TextChanged+=(s,e)=>hint.Visibility=search.Text.Length==0?Visibility.Visible:Visibility.Collapsed;tools.Children.Add(searchField);filter.ItemsSource=new[]{"Все записи","Ошибки","Замечания"};filter.SelectedIndex=0;filter.ToolTip="Показать все группы, ошибки или предупреждения.";Grid.SetColumn(filter,1);tools.Children.Add(filter);var actions=new StackPanel{Orientation=Orientation.Horizontal};var copy=new Button{Content="Копировать",ToolTip="Копировать раскрытые группы с учётом поиска и фильтра."};copy.Click+=(s,e)=>CopyRequested?.Invoke(this,EventArgs.Empty);var download=new Button{Content="Журналы",ToolTip="Скачать полные исходные журналы выбранного задания."};download.Click+=(s,e)=>DownloadRequested?.Invoke(this,EventArgs.Empty);var refresh=new Button{Content="↻",ToolTip="Обновить результат текущего задания. Новое задание не запускается."};refresh.Click+=(s,e)=>RefreshRequested?.Invoke(this,EventArgs.Empty);actions.Children.Add(copy);actions.Children.Add(download);actions.Children.Add(refresh);Grid.SetColumn(actions,2);tools.Children.Add(actions);DockPanel.SetDock(tools,Dock.Top);dock.Children.Add(tools);groups.Background=new SolidColorBrush(Color.FromRgb(16,34,57));scroll.Background=groups.Background;scroll.Content=groups;dock.Children.Add(scroll);Content=dock;search.TextChanged+=(s,e)=>Render();filter.SelectionChanged+=(s,e)=>Render();}
 public static List<(string Title,string Body)> Sections(string text){var result=new List<(string,string)>();string title="Результат",body="";foreach(var line in text.Replace("\r\n","\n").Split('\n')){if(line.StartsWith("## ")){if(body.Trim().Length>0)result.Add((title,body.TrimEnd()));title=line[3..];body="";}else body+=line+"\n";}if(body.Trim().Length>0)result.Add((title,body.TrimEnd()));return result;}
 public string VisibleText()=>string.Join(Environment.NewLine+Environment.NewLine,groups.Children.OfType<Expander>().Where(e=>e.IsExpanded).Select(e=>((e.Header as TextBlock)?.Text??e.Header.ToString())+Environment.NewLine+(e.Tag as string??"")));
 public void SetExpanded(string title,bool open){expanded[title]=open;Render();}
 public static string LineTone(string line){if(Regex.IsMatch(line,@"(?i)ошибок:\s*0\b|без замечаний|не обнаружила нарушений|отчётность работает"))return "Success";if(Regex.IsMatch(line,@"(?i)предупреж|неполн|частичн|не расшифр|не подтвержд|ограничени|рекомендаци|WARNING|retry"))return "Warning";if(LogPresentation.Anomaly(line))return "Error";if(Regex.IsMatch(line,@"(?i)успешно|получен сервером|Succeeded|Очистка очереди.*не требуется"))return "Success";return "Normal";}
 void Render(){if(groups==null)return;double offset=scroll.VerticalOffset;groups.Children.Clear();foreach(var (title,body) in Sections(Text??"")){string display=body;if(filter.SelectedIndex==1)display=LogPresentation.ErrorContext(body);if(filter.SelectedIndex==2)display=string.Join("\n",body.Split('\n').Where(x=>x.Contains("предупреж",StringComparison.OrdinalIgnoreCase)||x.Contains("retry",StringComparison.OrdinalIgnoreCase)||x.Contains("falling back",StringComparison.OrdinalIgnoreCase)));if(filter.SelectedIndex>0&&(display.Length==0||display.StartsWith("В выбранном интервале")))continue;if(search.Text.Length>0){var lines=display.Split('\n');var hits=Enumerable.Range(0,lines.Length).Where(i=>lines[i].Contains(search.Text,StringComparison.OrdinalIgnoreCase)).SelectMany(i=>Enumerable.Range(Math.Max(0,i-1),Math.Min(lines.Length-1,i+1)-Math.Max(0,i-1)+1)).Distinct().Order().Select(i=>lines[i]);display=string.Join("\n",hits);if(display.Length==0)continue;}var expander=new Expander{Header=new TextBlock{Text=title,Foreground=Brushes.White,FontWeight=FontWeights.SemiBold,Padding=new(6,5,6,5)},Background=new SolidColorBrush(Color.FromRgb(35,58,82)),Foreground=Brushes.White,Margin=new(0,0,0,1),IsExpanded=expanded.TryGetValue(title,out bool open)?open:!title.StartsWith("Технический")&&!title.StartsWith("Сбор диагностики")};var document=new FlowDocument{PagePadding=new(0)};var paragraph=new Paragraph{Margin=new(0)};foreach(var line in display.Split('\n')){string tone=LineTone(line);var run=new Run(line){Foreground=tone=="Error"?Brushes.Salmon:tone=="Warning"?Brushes.Gold:tone=="Success"?Brushes.LightGreen:new SolidColorBrush(Color.FromRgb(215,230,250))};if(tone is "Error" or "Warning")run.FontWeight=FontWeights.SemiBold;paragraph.Inlines.Add(run);paragraph.Inlines.Add(new LineBreak());}document.Blocks.Add(paragraph);var box=new RichTextBox{Document=document,IsReadOnly=true,IsDocumentEnabled=false,FontFamily=new FontFamily("Consolas"),Background=new SolidColorBrush(Color.FromRgb(16,34,57)),BorderThickness=new(0),Padding=new(8),VerticalScrollBarVisibility=ScrollBarVisibility.Disabled,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};expander.Tag=display;expander.Content=box;expander.Expanded+=(s,e)=>expanded[title]=true;expander.Collapsed+=(s,e)=>expanded[title]=false;groups.Children.Add(expander);}scroll.ScrollToVerticalOffset(offset);if(AutoScroll)scroll.ScrollToEnd();}
}
