using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using DomainConsole.Shared;
namespace DomainConsole;
public sealed class LogViewer:UserControl {
 public static readonly DependencyProperty TextProperty=DependencyProperty.Register(nameof(Text),typeof(string),typeof(LogViewer),new PropertyMetadata("",(d,e)=>((LogViewer)d).Render()));
 public string Text {get=>(string)GetValue(TextProperty);set=>SetValue(TextProperty,value);}
 readonly StackPanel groups=new();readonly ScrollViewer scroll=new(){VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};
 readonly TextBox search=new(){MinWidth=70,ToolTip="Найти текст в отображаемых группах журнала."};readonly ComboBox filter=new(){Width=115};readonly CheckBox follow=new(){Content="Автопрокрутка",ToolTip="Прокручивать журнал к последним записям при обновлении."};
 readonly Dictionary<string,bool> expanded=new();
 public LogViewer(){var dock=new DockPanel();var tools=new Grid{Margin=new(0,0,0,6)};tools.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});tools.ColumnDefinitions.Add(new(){Width=GridLength.Auto});tools.ColumnDefinitions.Add(new(){Width=GridLength.Auto});search.Margin=new(0,0,6,0);search.ToolTip="Поиск по тексту журнала";var searchField=new Grid();searchField.Children.Add(search);var hint=new TextBlock{Text="Поиск в журнале",Margin=new(6,6,0,0),Foreground=Brushes.SlateGray,IsHitTestVisible=false};searchField.Children.Add(hint);search.TextChanged+=(s,e)=>hint.Visibility=search.Text.Length==0?Visibility.Visible:Visibility.Collapsed;tools.Children.Add(searchField);filter.ItemsSource=new[]{"Все записи","Ошибки","Замечания"};filter.SelectedIndex=0;filter.ToolTip="Показать все группы, ошибки или предупреждения.";Grid.SetColumn(filter,1);tools.Children.Add(filter);follow.Margin=new(8,4,0,0);Grid.SetColumn(follow,2);tools.Children.Add(follow);DockPanel.SetDock(tools,Dock.Top);dock.Children.Add(tools);scroll.Content=groups;dock.Children.Add(scroll);Content=dock;search.TextChanged+=(s,e)=>Render();filter.SelectionChanged+=(s,e)=>Render();}
 public static List<(string Title,string Body)> Sections(string text){var result=new List<(string,string)>();string title="Результат",body="";foreach(var line in text.Replace("\r\n","\n").Split('\n')){if(line.StartsWith("## ")){if(body.Trim().Length>0)result.Add((title,body.TrimEnd()));title=line[3..];body="";}else body+=line+"\n";}if(body.Trim().Length>0)result.Add((title,body.TrimEnd()));return result;}
 void Render(){if(groups==null)return;double offset=scroll.VerticalOffset;groups.Children.Clear();foreach(var (title,body) in Sections(Text??"")){string display=body;if(filter.SelectedIndex==1)display=LogPresentation.ErrorContext(body);if(filter.SelectedIndex==2)display=string.Join("\n",body.Split('\n').Where(x=>x.Contains("предупреж",StringComparison.OrdinalIgnoreCase)||x.Contains("retry",StringComparison.OrdinalIgnoreCase)||x.Contains("falling back",StringComparison.OrdinalIgnoreCase)));if(filter.SelectedIndex>0&&(display.Length==0||display.StartsWith("В выбранном интервале")))continue;if(search.Text.Length>0){var lines=display.Split('\n');var hits=Enumerable.Range(0,lines.Length).Where(i=>lines[i].Contains(search.Text,StringComparison.OrdinalIgnoreCase)).SelectMany(i=>Enumerable.Range(Math.Max(0,i-1),Math.Min(lines.Length-1,i+1)-Math.Max(0,i-1)+1)).Distinct().Order().Select(i=>lines[i]);display=string.Join("\n",hits);if(display.Length==0)continue;}var expander=new Expander{Header=title,Margin=new(0,0,0,7),IsExpanded=expanded.TryGetValue(title,out bool open)?open:!title.StartsWith("Технический")&&!title.StartsWith("Сбор диагностики")};var box=new TextBox{Text=display,IsReadOnly=true,TextWrapping=TextWrapping.Wrap,FontFamily=new FontFamily("Consolas"),Background=new SolidColorBrush(Color.FromRgb(16,34,57)),Foreground=new SolidColorBrush(Color.FromRgb(215,230,250)),BorderThickness=new(0),Padding=new(8),VerticalScrollBarVisibility=ScrollBarVisibility.Disabled};expander.Content=box;expander.Expanded+=(s,e)=>expanded[title]=true;expander.Collapsed+=(s,e)=>expanded[title]=false;groups.Children.Add(expander);}scroll.ScrollToVerticalOffset(offset);if(follow.IsChecked==true)scroll.ScrollToEnd();}
}
