using System.Collections.ObjectModel;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using DomainConsole.Shared;
namespace DomainConsole;
public sealed class CachedWsusReport {public WsusReport Report {get;set;}=new();public string Server {get;set;}="";public string ReceivedUtc {get;set;}="";public string Started {get;set;}="";}
public partial class MainWindow {
 public ObservableCollection<ComputerRow> RecentComputers {get;}=new();
 readonly List<string> recentHosts=Store.Read("recent-computers.json",new List<string>());
 readonly Dictionary<string,CachedWsusReport> reportCache=new(Store.Read("wsus-report-cache.json",new Dictionary<string,CachedWsusReport>()),StringComparer.OrdinalIgnoreCase);
 readonly HashSet<string> liveReports=new(StringComparer.OrdinalIgnoreCase);
 readonly HashSet<string> confirmedJobs=new(StringComparer.OrdinalIgnoreCase);
 bool updatingRecent;int recentLimit=Store.Read("recent-limit.json",20);
 void RestoreNavigation(){recentLimit=Math.Clamp(recentLimit,5,200);RecentLimitBox.Text=recentLimit.ToString();LimitBox.Text=Store.Read("parallel-limit.json",0).ToString();RecentGroup.IsExpanded=viewState.RecentExpanded;TreeGroup.IsExpanded=viewState.TreeExpanded;ApplyNavigationLayout();foreach(var entry in reportCache){serverReports[entry.Key]=CachedReportText(entry.Value);reportSeverity[entry.Key]=entry.Value.Report.Severity(entry.Value.Started);}if(recentHosts.Count==0)foreach(var host in History.SelectMany(j=>j.Targets.Select(t=>t.Host)).Distinct(StringComparer.OrdinalIgnoreCase).Take(recentLimit))recentHosts.Add(host);}
 static string CachedReportText(CachedWsusReport cached)=>"Сохранённые данные; получены: "+LocalDateConverter.Format(cached.ReceivedUtc)+". Текущее состояние не запрашивалось.\n"+System.Text.RegularExpressions.Regex.Replace(cached.Report.Format(cached.Server,cached.Started),@"(?m)^Получено:.*$","Снимок: "+LocalDateConverter.Format(cached.ReceivedUtc));
 void RememberComputer(string host){recentHosts.RemoveAll(h=>h.Equals(host,StringComparison.OrdinalIgnoreCase));recentHosts.Insert(0,host);if(recentHosts.Count>200)recentHosts.RemoveRange(200,recentHosts.Count-200);Store.Write("recent-computers.json",recentHosts);RefreshRecent();}
 void RefreshRecent(){if(RecentList==null||updatingRecent)return;int activeCount=History.SelectMany(j=>j.Targets).Where(t=>t.Status is "Queued" or "Sending" or "Submitted" or "Running").Select(t=>t.Host).Distinct(StringComparer.OrdinalIgnoreCase).Count();RecentGroup.Header="Последние в работе"+(activeCount>0?" · активно: "+activeCount:"");TreeGroup.Header="Дерево AD"+(activeCount>0?" · активно: "+activeCount:"");updatingRecent=true;try{var active=History.SelectMany(j=>j.Targets).Where(t=>t.Status is "Queued" or "Sending" or "Submitted" or "Running"||t.State?.DiagnosticStatus is "Pending" or "Running").Select(t=>t.Host);var hosts=recentHosts.Take(recentLimit).Concat(active).Distinct(StringComparer.OrdinalIgnoreCase).ToList();var wanted=new List<ComputerRow>();foreach(var host in hosts){var row=Computers.FirstOrDefault(r=>r.Host.Equals(host,StringComparison.OrdinalIgnoreCase));if(row==null){var identity=History.SelectMany(j=>j.Targets).FirstOrDefault(t=>t.Host.Equals(host,StringComparison.OrdinalIgnoreCase));if(identity!=null){row=WithHistory(identity);Computers.Add(row);}}if(row!=null)wanted.Add(row);}if(!RecentComputers.SequenceEqual(wanted)){RecentComputers.Clear();foreach(var row in wanted)RecentComputers.Add(row);}if(ComputerGrid.SelectedItem is ComputerRow selected)RecentList.SelectedItem=RecentComputers.FirstOrDefault(r=>r.Host.Equals(selected.Host,StringComparison.OrdinalIgnoreCase));}finally{updatingRecent=false;}}
 void RecentCheck_Click(object sender,RoutedEventArgs e)=>UpdateSelectionCount();
 void Recent_Changed(object sender,SelectionChangedEventArgs e){if(!loadingRows&&!updatingRecent&&RecentList.SelectedItem is ComputerRow row){historyViewId="";ComputerGrid.SelectedItem=row;ShowCurrent();RefreshOutcomes();}}
 void NavigationGroup_Changed(object sender,RoutedEventArgs e){if(e.Source!=sender||RecentGroup==null||TreeGroup==null||RecentRow==null)return;ApplyNavigationLayout();if(IsLoaded){viewState.RecentExpanded=RecentGroup.IsExpanded;viewState.TreeExpanded=TreeGroup.IsExpanded;Store.Write("view-state.json",viewState);}}
 void ApplyNavigationLayout(){double ratio=Math.Clamp(viewState.RecentRatio,0.15,0.85);RecentRow.Height=RecentGroup.IsExpanded?new GridLength(ratio,GridUnitType.Star):GridLength.Auto;TreeRow.Height=TreeGroup.IsExpanded?new GridLength(1-ratio,GridUnitType.Star):GridLength.Auto;NavigationSplitter.Visibility=RecentGroup.IsExpanded&&TreeGroup.IsExpanded?Visibility.Visible:Visibility.Collapsed;}
 void NavigationSplit_Changed(object sender,DragCompletedEventArgs e){double sum=RecentRow.Height.Value+TreeRow.Height.Value;if(sum>0)viewState.RecentRatio=RecentRow.Height.Value/sum;Store.Write("view-state.json",viewState);}
 void SaveNavigation_Click(object sender,RoutedEventArgs e)=>Guard(()=>{if(!int.TryParse(RecentLimitBox.Text,out var n)||n<5||n>200)throw new Exception("Количество последних компьютеров: 5–200.");if(!int.TryParse(LimitBox.Text,out var parallel)||parallel<0)throw new Exception("Параллельность: целое число от 0.");recentLimit=n;limit=parallel;Store.Write("recent-limit.json",n);Store.Write("parallel-limit.json",parallel);RefreshRecent();Notify("Параметры навигации и выполнения сохранены.");});
 void RefreshActivity(){string focused=(ComputerGrid.SelectedItem as ComputerRow)?.Host??"";foreach(var row in Computers){var targets=History.SelectMany(j=>j.Targets).Where(t=>t.Host.Equals(row.Host,StringComparison.OrdinalIgnoreCase)).ToList();var active=targets.FirstOrDefault(t=>t.Status is "Queued" or "Sending" or "Submitted" or "Running"||t.State?.DiagnosticStatus is "Pending" or "Running");var latest=ExecutionRow(row,MainTabs.SelectedItem==WsusTab).Target;string stamp=latest?.State?.Ended??latest?.State?.Updated??"";var activeJob=active==null?null:History.FirstOrDefault(j=>j.Targets.Contains(active));bool confirmed=activeJob!=null&&confirmedJobs.Contains(activeJob.Id+row.Host);row.SetActivity(active!=null&&confirmed,active?.State?.Progress,active!=null?(confirmed?"● "+ComputerRow.StatusText(active.Status):"Состояние требует проверки"):DateTimeOffset.TryParse(stamp,out var at)?at.ToLocalTime().ToString("dd.MM HH:mm")+" · "+ComputerRow.StatusText(latest!.Status):"Не проверен",row.Host.Equals(focused,StringComparison.OrdinalIgnoreCase));}RefreshRecent();if(WsusStopButton!=null){var row=ComputerGrid.SelectedItem as ComputerRow;WsusStopButton.IsEnabled=row!=null&&ExecutionRow(row,true).Target.Status is "Queued" or "Sending" or "Submitted" or "Running";}if(StopButton!=null){var row=ComputerGrid.SelectedItem as ComputerRow;StopButton.IsEnabled=row!=null&&ActiveRow().Target.Status is "Queued" or "Sending" or "Submitted" or "Running";}}
 void SaveReportCache(string host,WsusReport report,string server,string started){reportCache[host]=new(){Report=report,Server=server,Started=started,ReceivedUtc=DateTime.UtcNow.ToString("o")};liveReports.Add(host);Store.Write("wsus-report-cache.json",reportCache);RememberComputer(host);}
 void VerifyNavigation(){bool restart=Environment.GetEnvironmentVariable("DOMAINCONSOLE_EXPECT_HISTORY")=="1";if(restart&&(!reportCache.ContainsKey("test-1.invalid")||!serverReports["test-1.invalid"].Contains("Сохранённые данные")))throw new Exception("WSUS snapshot not restored");if(restart&&(!recentHosts.Contains("test-1.invalid")||viewState.RecentExpanded))throw new Exception("Recent navigation not restored");SaveReportCache("test-1.invalid",new(){LastReportedUtc=DateTime.UtcNow.ToString("o"),LastSyncResult="Succeeded"},"wsus.invalid:8530","");RecentGroup.IsExpanded=false;NavigationGroup_Changed(RecentGroup,new RoutedEventArgs(Expander.CollapsedEvent,RecentGroup));if(new LocalDateConverter().Convert(DateTime.UtcNow.ToString("o"),typeof(string),"Short",System.Globalization.CultureInfo.InvariantCulture).ToString()!.Contains("+"))throw new Exception("History timezone still shown");var original=new RemoteJob{Steps=new(){new(){Code="hostname\nipconfig",Kind="CMD"}}};var details=new HistoryDetails(this,original);details.Editors[0].Text="EDITED";if(original.Steps[0].Code.Contains("EDITED")||!original.CommandPreview.Contains("ipconfig"))throw new Exception("History editing changed original commands");if(LogViewer.LineTone("Ошибок: 0")!="Success"||LogViewer.LineTone("Ошибка: 0x80070005")!="Error")throw new Exception("Log highlighting misclassifies results");}
}
