using System.Windows;
using System.Windows.Controls;
namespace DomainConsole;
public sealed class TargetConfirmation:Window {
 readonly ComputerRow? current;readonly List<ComputerRow> marked;readonly RadioButton only=new(),all=new();readonly TextBlock summary=new();readonly ListBox targets=new();
 public List<ComputerRow>? Result {get;private set;}public bool BatchChosen {get;private set;}
 public TargetConfirmation(Window owner,ComputerRow? focused,List<ComputerRow> checkedRows,string preview){Owner=owner;current=focused;marked=checkedRows;Title="Подтверждение действия и целей";Width=620;Height=560;MinHeight=460;WindowStartupLocation=WindowStartupLocation.CenterOwner;Background=System.Windows.Media.Brushes.White;
  var panel=new DockPanel{Margin=new(20)};Content=panel;var actions=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};DockPanel.SetDock(actions,Dock.Bottom);var cancel=new Button{Content="Отмена",IsCancel=true,ToolTip="Закрыть окно без отправки задания. Галочки сохраняются."};var run=new Button{Content="Выполнить",IsDefault=true,ToolTip="Отправить действие только на цели из списка выше."};run.Click+=(s,e)=>{BatchChosen=all.IsChecked==true;Result=ResolveTargets(current,marked,BatchChosen);if(Result.Count>0)DialogResult=true;};actions.Children.Add(cancel);actions.Children.Add(run);panel.Children.Add(actions);
  var top=new StackPanel();DockPanel.SetDock(top,Dock.Top);top.Children.Add(new TextBlock{Text="Где выполнить действие?",FontSize=20,FontWeight=FontWeights.SemiBold,Margin=new(0,0,0,12)});only.Content=current==null?"Текущий компьютер не выбран":"Только текущий: "+current.Name;only.GroupName="scope";only.IsEnabled=current!=null;only.IsChecked=current!=null;only.ToolTip="Остальные галочки не влияют на этот запуск.";all.Content="Все отмеченные: "+marked.Count;all.GroupName="scope";all.IsEnabled=marked.Count>0;all.IsChecked=current==null&&marked.Count>0;all.ToolTip="Список ниже — точный набор целей. После принятия массового запуска галочки снимутся.";only.Checked+=(s,e)=>Refresh();all.Checked+=(s,e)=>Refresh();top.Children.Add(only);top.Children.Add(all);top.Children.Add(summary);targets.Height=100;targets.DisplayMemberPath="Name";top.Children.Add(targets);panel.Children.Add(top);
  panel.Children.Add(new TextBox{Text=preview,IsReadOnly=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,FontFamily=new("Consolas"),Margin=new(0,12,0,12)});Refresh();}
 void Refresh(){var rows=ResolveTargets(current,marked,all.IsChecked==true);targets.ItemsSource=rows;summary.Text="Целей: "+rows.Count+" · запуск от SYSTEM на целевых компьютерах";}
 public static List<ComputerRow> ResolveTargets(ComputerRow? current,IEnumerable<ComputerRow> marked,bool batch)=>batch?marked.DistinctBy(r=>r.Host,StringComparer.OrdinalIgnoreCase).ToList():current==null?new():new(){current};
}
