using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Management;
using System.Text.RegularExpressions;
using System.Web.Script.Serialization;
using DomainConsole.Shared;
namespace DomainConsole.Agent {
 internal sealed class ClientCleanup {
  static readonly JavaScriptSerializer Json=new JavaScriptSerializer();
  public static bool Finished(RemoteState state){return state!=null&&DateTimeOffset.TryParse(state.Ended,out _)&&new[]{"Completed","CompletedWithErrors","Failed","Cancelled","VerifiedAfterReboot"}.Contains(state.Status)&&state.DiagnosticStatus!="Pending"&&state.DiagnosticStatus!="Running"&&state.DiagnosticStatus!="LegacyRunning"&&state.RestoreStatus!="Pending"&&state.RestoreStatus!="InterventionRequired"&&!state.RebootRequired;}
  static string Hash(string path){using(var sha=System.Security.Cryptography.SHA256.Create())using(var input=File.OpenRead(path))return BitConverter.ToString(sha.ComputeHash(input)).Replace("-","");}
  static bool NoLinks(string path){foreach(var item in Directory.GetFileSystemEntries(path)){if(!Safe(item))return false;if(Directory.Exists(item)&&!NoLinks(item))return false;}return true;}
  static bool Safe(string path)=>!File.GetAttributes(path).HasFlag(FileAttributes.ReparsePoint);
  public static int Run(string root){root=Path.GetFullPath(root).TrimEnd(Path.DirectorySeparatorChar,Path.AltDirectorySeparatorChar);if(!Directory.Exists(root)||!Safe(root))return 2;var report=new List<string>();
   try{var active=new List<string>();var binaries=new HashSet<string>(StringComparer.OrdinalIgnoreCase);using(var query=new ManagementObjectSearcher("SELECT ExecutablePath,CommandLine FROM Win32_Process WHERE Name='DomainConsole.Agent.exe'"))using(var processes=query.Get()){foreach(ManagementObject process in processes){active.Add((string)process["CommandLine"]??"");var exe=(string)process["ExecutablePath"];if(exe!=null)binaries.Add(exe);}}
    dynamic scheduler=Activator.CreateInstance(Type.GetTypeFromProgID("Schedule.Service"));scheduler.Connect();dynamic folder=scheduler.GetFolder("\\");dynamic tasks=folder.GetTasks(1);var refs=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);var running=new HashSet<string>(StringComparer.OrdinalIgnoreCase);for(int i=1;i<=tasks.Count;i++){dynamic task=tasks.Item(i);string name=task.Name;try{dynamic action=task.Definition.Actions.Item(1);string exe=action.Path;string args=action.Arguments;if(exe!=null&&Path.GetFullPath(exe).StartsWith(root+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)&&Path.GetFileName(exe).Equals("DomainConsole.Agent.exe",StringComparison.OrdinalIgnoreCase)){refs[name]=exe;if((int)task.State==4)running.Add(name);}}catch{if(name.StartsWith("DomainConsoleCSharp-",StringComparison.Ordinal))throw;}}
    int copiedDays=7,uncopiedDays=30;var config=Path.Combine(root,"retention.json");if(File.Exists(config)){dynamic values=Json.DeserializeObject(File.ReadAllText(config));copiedDays=Math.Max(1,Math.Min(365,(int)values["CopiedDays"]));uncopiedDays=Math.Max(copiedDays,Math.Min(365,(int)values["UncopiedDays"]));}
    foreach(var path in Directory.GetDirectories(root)){Guid id;if(!Guid.TryParseExact(Path.GetFileName(path),"D",out id)||!Safe(path))continue;try{var statePath=Path.Combine(path,"status.json");var jobPath=Path.Combine(path,"job.json");if(!File.Exists(statePath)||!File.Exists(jobPath))continue;var state=Json.Deserialize<RemoteState>(File.ReadAllText(statePath));var job=Json.Deserialize<RemoteJob>(File.ReadAllText(jobPath));if(state.Id!=id.ToString()||job.Id!=id.ToString()||!Finished(state)||active.Any(s=>s.IndexOf(path,StringComparison.OrdinalIgnoreCase)>=0))continue;var main="DomainConsoleCSharp-"+id;var recovery=new[]{"DomainConsoleCSharp-Restore-"+id,"DomainConsoleCSharp-Verify-"+id};if(recovery.Any(refs.ContainsKey)||running.Contains(main))continue;if(refs.ContainsKey(main)){folder.DeleteTask(main,0);refs.Remove(main);report.Add("Удалено завершённое задание "+id);}
     var legacy=Path.Combine(path,"DomainConsole.Agent.exe");if(File.Exists(legacy)&&!binaries.Contains(legacy)&&!refs.Values.Contains(legacy,StringComparer.OrdinalIgnoreCase)){File.Delete(legacy);report.Add("Удалена лишняя копия агента "+id);}
     DateTimeOffset ended;if(!DateTimeOffset.TryParse(state.Ended,out ended))continue;int days=uncopiedDays;var ack=Path.Combine(path,"archived.json");if(File.Exists(ack)){var values=Json.Deserialize<Dictionary<string,string>>(File.ReadAllText(ack));DateTimeOffset saved;if(values.ContainsKey("StateHash")&&values["StateHash"]==Hash(statePath)&&values.ContainsKey("SavedUtc")&&DateTimeOffset.TryParse(values["SavedUtc"],out saved)){ended=saved;days=copiedDays;}}
     if(DateTimeOffset.UtcNow-ended>TimeSpan.FromDays(days)){// refuse any nested reparse points, including files
      if(!NoLinks(path)){report.Add("Пропущена папка с ссылками "+id);continue;}Directory.Delete(path,true);report.Add("Удалены истёкшие журналы "+id);}
    }catch(Exception ex){report.Add(Path.GetFileName(path)+": "+ex.Message);}}
    var cache=Path.Combine(root,"Agent");if(Directory.Exists(cache)&&Safe(cache)){foreach(var path in Directory.GetDirectories(cache)){if(!Regex.IsMatch(Path.GetFileName(path),"^[0-9a-f]{64}$")||!Safe(path))continue;var exe=Path.Combine(path,"DomainConsole.Agent.exe");if(binaries.Contains(exe)||refs.Values.Contains(exe,StringComparer.OrdinalIgnoreCase))continue;if(!NoLinks(path))continue;Directory.Delete(path,true);report.Add("Удалена неиспользуемая версия агента "+Path.GetFileName(path));}}
    File.WriteAllText(Path.Combine(root,"cleanup-last.log"),DateTimeOffset.UtcNow.ToString("o")+Environment.NewLine+string.Join(Environment.NewLine,report));return 0;
   }catch(Exception ex){Console.Error.WriteLine(ex);return 1;}
  }
  public static int Smoke(string root){Directory.CreateDirectory(root);var ids=new List<string>();Func<string,int,string,string,string> create=(status,days,diagnostic,restore)=>{var id=Guid.NewGuid().ToString();ids.Add(id);var folder=Path.Combine(root,id);Directory.CreateDirectory(folder);File.WriteAllText(Path.Combine(folder,"job.json"),Json.Serialize(new RemoteJob{Id=id}));File.WriteAllText(Path.Combine(folder,"status.json"),Json.Serialize(new RemoteState{Id=id,Status=status,Ended=DateTime.UtcNow.AddDays(-days).ToString("o"),DiagnosticStatus=diagnostic,RestoreStatus=restore}));File.WriteAllText(Path.Combine(folder,"result.out"),"PRESERVE_RESULT");File.WriteAllText(Path.Combine(folder,"DomainConsole.Agent.exe"),"legacy");return folder;};
   var expired=create("Completed",40,"Completed","NotRequested");var fresh=create("Completed",1,"NotRequested","NotRequested");var active=create("Running",40,"NotRequested","NotRequested");var diagnostic=create("Completed",40,"Running","NotRequested");var recovery=create("Completed",40,"Completed","Pending");var reboot=create("AwaitingReboot",40,"Completed","NotRequested");var copied=create("Failed",2,"Completed","NotRequested");File.WriteAllText(Path.Combine(copied,"archived.json"),Json.Serialize(new Dictionary<string,string>{{"SavedUtc",DateTime.UtcNow.AddDays(-10).ToString("o")},{"StateHash",Hash(Path.Combine(copied,"status.json"))}}));var outside=Path.Combine(root,"outside");Directory.CreateDirectory(outside);File.WriteAllText(Path.Combine(outside,"sentinel"),"KEEP");var linked=create("Completed",40,"Completed","NotRequested");using(var process=ProcessStart("cmd.exe","/c mklink /J \""+Path.Combine(linked,"link")+"\" \""+outside+"\"")){process.WaitForExit();if(process.ExitCode!=0)throw new Exception("Cannot create junction fixture");}
   if(Run(root)!=0)throw new Exception("Cleanup failed");if(Directory.Exists(expired)||Directory.Exists(copied)||!Directory.Exists(fresh)||File.Exists(Path.Combine(fresh,"DomainConsole.Agent.exe"))||!File.Exists(Path.Combine(fresh,"result.out"))||!Directory.Exists(active)||!Directory.Exists(diagnostic)||!Directory.Exists(recovery)||!Directory.Exists(reboot)||!Directory.Exists(linked)||!File.Exists(Path.Combine(outside,"sentinel")))throw new Exception("Retention/active/recovery/junction protection failed");Console.WriteLine("Cleanup age, archives, legacy binaries, active diagnostics, reboot/recovery and junction protection passed.");return 0;
  }
  static System.Diagnostics.Process ProcessStart(string exe,string arguments){return System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(exe,arguments){UseShellExecute=false,CreateNoWindow=true});}
  public static void RemoveLaunchTask(string id){try{dynamic scheduler=Activator.CreateInstance(Type.GetTypeFromProgID("Schedule.Service"));scheduler.Connect();scheduler.GetFolder("\\").DeleteTask("DomainConsoleCSharp-"+id,0);}catch{}}
 }
}
