using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Runtime.InteropServices;
using DomainConsole.Shared;
namespace DomainConsole.Agent {
 public sealed class FakeSearchJob {public bool IsCompleted=>true;public int Cleanups;public void CleanUp(){Cleanups++;}}
 public sealed class FakeSearcher {public int Calls;public int Failures=2;public FakeSearchJob Last;public object BeginSearch(string criteria,object callback,object state){Last=new FakeSearchJob();return Last;}public object EndSearch(object job){Calls++;if(Calls<=Failures)throw new COMException("fixture trips",unchecked((int)0x80244010));return new FakeSearchResult();}}
 public sealed class FakeSearchResult {public int ResultCode=>2;}
 public sealed class FakeProgress {public int PercentComplete {get;set;}public string TotalBytesDownloaded {get;set;}="0";public string TotalBytesToDownload {get;set;}="1000";}
 public sealed class FakeOperation {public volatile bool completed;public bool IsCompleted=>completed;public bool Aborted;public FakeProgress Progress=new FakeProgress();public object GetProgress()=>Progress;public void RequestAbort(){Aborted=true;}}
 internal static partial class Program {
  static int UpdateSmoke(string folder){Directory.CreateDirectory(folder);Folder=folder;Job=new RemoteJob{OutputChannel="WSUS",Steps=new System.Collections.Generic.List<CommandStep>{new CommandStep{Kind="UpdateScan"}}};State=new RemoteState{Status="Running"};Stage("Скачивание · fixture");var callback=new UpdateCallback();foreach(var type in new[]{typeof(ISearchDone),typeof(IDownloadDone),typeof(IInstallDone),typeof(IDownloadChanged),typeof(IInstallChanged)}){IntPtr ptr=Marshal.GetComInterfaceForObject(callback,type);Marshal.Release(ptr);}var fake=new FakeOperation();var worker=Task.Run(()=>WaitUpdate(fake,"Скачивание"));Thread.Sleep(1200);fake.Progress.PercentComplete=30;fake.Progress.TotalBytesDownloaded="300";Thread.Sleep(1200);File.WriteAllText(FilePath("stop-now.flag"),"");Thread.Sleep(1500);if(!fake.Aborted||State.StopStatus!="AbortRequested"||worker.IsCompleted)throw new Exception("Cancellation incorrectly reported operation completed");fake.completed=true;if(!worker.Wait(5000))throw new Exception("Operation completion not observed");if(State.Progress!=30||!State.TransferText.Contains("МБ")||string.IsNullOrEmpty(State.LastMovementUtc))throw new Exception("Download progress missing");File.Delete(FilePath("stop-now.flag"));if(!ExecutionLane().EndsWith("WSUS"))throw new Exception("WSUS lane missing");Job.OutputChannel="Commands";Job.Steps[0].Kind="CMD";if(!ExecutionLane().EndsWith("Commands"))throw new Exception("Separate command lane missing");ApplyRecommendation("0x80240034");if(State.RecommendationAction!="Download")throw new Exception("Download recommendation missing");
   Stage("Status sharing fixture");var path=FilePath("status.json");string original=File.ReadAllText(path);using(var reader=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read)){State.Stage="locked write";Save();if(!statusWritePending||File.ReadAllText(path)!=original)throw new Exception("Locked status aborted or destroyed prior state");}nextStatusWrite=DateTime.MinValue;Save();if(statusWritePending||!File.ReadAllText(path).Contains("locked write"))throw new Exception("Status recovery lost pending state");
   var delays=(int[])SearchRetrySeconds.Clone();try{SearchRetrySeconds[0]=3;var waitingSearch=new FakeSearcher{Failures=99};var waitingTask=Task.Run(()=>SearchWithRetry(waitingSearch));Thread.Sleep(500);File.WriteAllText(FilePath("cancel.flag"),"");try{if(!waitingTask.Wait(5000))throw new Exception("Retry countdown ignored cancellation");throw new Exception("Retry cancellation falsely succeeded");}catch(AggregateException ex){if(!(ex.GetBaseException() is OperationCanceledException)||waitingSearch.Calls!=1)throw;}finally{File.Delete(FilePath("cancel.flag"));}for(int i=0;i<SearchRetrySeconds.Length;i++)SearchRetrySeconds[i]=0;var search=new FakeSearcher();SearchWithRetry(search);if(search.Calls!=3||search.Last.Cleanups!=1)throw new Exception("Search retry or COM cleanup failed");search=new FakeSearcher{Failures=99};try{SearchWithRetry(search);throw new Exception("Search retry limit missing");}catch(COMException){if(search.Calls!=6)throw new Exception("Expected initial plus five retries");}File.WriteAllText(FilePath("cancel.flag"),"");try{SearchWithRetry(new FakeSearcher());throw new Exception("Search cancellation missing");}catch(OperationCanceledException){}finally{File.Delete(FilePath("cancel.flag"));}}finally{Array.Copy(delays,SearchRetrySeconds,delays.Length);}
   Stage("Transfer retry fixture");fake=new FakeOperation();fake.Progress.PercentComplete=103;fake.Progress.TotalBytesDownloaded="1100";fake.Progress.TotalBytesToDownload="1000";var overflow=Task.Run(()=>WaitUpdate(fake,"Скачивание"));Thread.Sleep(1200);fake.completed=true;if(!overflow.Wait(5000)||State.Progress.HasValue||!State.TransferText.Contains("уточняется"))throw new Exception("Inconsistent WUA transfer displayed as completion");
   Console.WriteLine("Status lock recovery, six-attempt search limit, cancellation and transfer overflow verified.");Console.WriteLine("WUA callbacks, download progress, cancellation acknowledgement and execution lanes verified");return 0;}
 }
}

