using System;
using System.IO;
using System.Linq;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using System.Runtime.InteropServices;
namespace DomainConsole.Agent {
 [ComVisible(true),Guid("88aee058-d4b0-4725-a2f1-814a67ae964c"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]public interface ISearchDone {void Invoke([MarshalAs(UnmanagedType.Interface)]object job,[MarshalAs(UnmanagedType.Interface)]object args);}
 [ComVisible(true),Guid("77254866-9f5b-4c8e-b9e2-c77a8530d64b"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]public interface IDownloadDone {void Invoke([MarshalAs(UnmanagedType.Interface)]object job,[MarshalAs(UnmanagedType.Interface)]object args);}
 [ComVisible(true),Guid("45f4f6f3-d602-4f98-9a8a-3efa152ad2d3"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]public interface IInstallDone {void Invoke([MarshalAs(UnmanagedType.Interface)]object job,[MarshalAs(UnmanagedType.Interface)]object args);}
 [ComVisible(true),Guid("8c3f1cdd-6173-4591-aebd-a56a53ca77c1"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]public interface IDownloadChanged {void Invoke([MarshalAs(UnmanagedType.Interface)]object job,[MarshalAs(UnmanagedType.Interface)]object args);}
 [ComVisible(true),Guid("e01402d5-f8da-43ba-a012-38894bd048f1"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]public interface IInstallChanged {void Invoke([MarshalAs(UnmanagedType.Interface)]object job,[MarshalAs(UnmanagedType.Interface)]object args);}
 [ComVisible(true),ClassInterface(ClassInterfaceType.None)]public sealed class UpdateCallback:ISearchDone,IDownloadDone,IInstallDone,IDownloadChanged,IInstallChanged {public void Invoke(object job,object args) {}}
 internal static partial class Program {
  static void ApplyRecommendation(string text){if(text.IndexOf("80240034",StringComparison.OrdinalIgnoreCase)>=0){State.Recommendation="Сбой скачивания. После завершения операции очистите Download и повторите поиск; также проверьте сеть и доступность содержимого WSUS.";State.RecommendationAction="Download";}else if(text.IndexOf("80070570",StringComparison.OrdinalIgnoreCase)>=0){State.Recommendation="Файл повреждён / нечитаем. Начните с очистки Download после завершения установки; при повторении проверьте DISM/SFC и диск.";State.RecommendationAction="Download";}else if(text.IndexOf("80072EE2",StringComparison.OrdinalIgnoreCase)>=0){State.Recommendation="Сетевой тайм-аут: проверьте фактический адрес назначения, прокси и доступ SYSTEM через Kerio. Очистка кэша по одному этому коду не рекомендуется.";State.RecommendationAction="Diagnosis";}else if(text.IndexOf("800F081F",StringComparison.OrdinalIgnoreCase)>=0){State.Recommendation="Проверьте совместимость источника восстановления и индекс образа; очистка очереди отчётности не требуется.";State.RecommendationAction="Diagnosis";}}
  static string ExecutionLane()=>@"Global\DomainConsoleCSharp.Execution."+(Job.Steps.All(s=>s.Kind=="ClientDiagnostics"||s.Kind=="Diagnostics")?"Diagnostics":(Job.QueueAfterWsus||Job.OutputChannel=="WSUS"||Job.MicrosoftSource||Job.ExclusiveMaintenance||Job.Steps.Any(s=>s.Kind=="Updates"||s.Kind=="UpdateScan"||s.Kind=="CacheCleanup"||s.Kind=="ReportRecovery")?"WSUS":"Commands"));
  static dynamic AsyncSearch(dynamic search){var callback=new UpdateCallback();dynamic operation=search.BeginSearch("IsInstalled=0 and IsHidden=0",callback,null);WaitUpdate(operation,"Поиск");dynamic result=search.EndSearch(operation);operation.CleanUp();GC.KeepAlive(callback);return result;}
  static dynamic AsyncDownload(dynamic downloader){var callback=new UpdateCallback();dynamic operation=downloader.BeginDownload(callback,callback,null);WaitUpdate(operation,"Скачивание");dynamic result=downloader.EndDownload(operation);operation.CleanUp();GC.KeepAlive(callback);return result;}
  static dynamic AsyncInstall(dynamic installer){var callback=new UpdateCallback();dynamic operation=installer.BeginInstall(callback,callback,null);WaitUpdate(operation,"Установка");dynamic result=installer.EndInstall(operation);operation.CleanUp();GC.KeepAlive(callback);return result;}
  static void WaitUpdate(dynamic operation,string phase){
   long bytes=-1,lastBytes=0;DateTime sample=DateTime.UtcNow;int percent=-1;DateTime movement=DateTime.UtcNow;DateTime? abort=null;bool diagnosed=false;Task diagnostic=null;var timer=Stopwatch.StartNew();
   while(!(bool)operation.IsCompleted){
    if(File.Exists(FilePath("stop-now.flag"))&&!abort.HasValue){try{operation.RequestAbort();State.StopStatus="AbortRequested";State.StopMessage="WUA принял запрос отмены; ожидается завершение текущего установщика";}catch(Exception ex){State.StopStatus="AwaitingSafePoint";State.StopMessage="Запрос отмены WUA не принят: "+ex.Message;}abort=DateTime.UtcNow;Save();}
    try{if(phase!="Поиск"){dynamic progress=operation.GetProgress();int current=(int)progress.PercentComplete;long transferred=phase=="Скачивание"?Convert.ToInt64(progress.TotalBytesDownloaded):-1;if(current!=percent||transferred!=bytes){percent=current;bytes=transferred;movement=DateTime.UtcNow;State.LastMovementUtc=movement.ToString("o");State.LastProgressUtc=State.LastMovementUtc;}State.Progress=current;State.ProgressValue=current.ToString();if(phase=="Скачивание"){long total=Convert.ToInt64(progress.TotalBytesToDownload);double seconds=Math.Max(0.1,(DateTime.UtcNow-sample).TotalSeconds);double speed=Math.Max(0,bytes-lastBytes)/seconds/1024.0;State.TransferText=string.Format("Скачано {0:F1} / {1:F1} МБ · {2:F1} КБ/с (последний замер)",bytes/1048576.0,total/1048576.0,speed);sample=DateTime.UtcNow;lastBytes=bytes;}}}catch(Exception ex){State.ActivityMessage="Промежуточный прогресс WUA недоступен: "+ex.Message;}
    int stall=Math.Max(1,Math.Min(120,Job.StallMinutes));if(DateTime.UtcNow-movement>TimeSpan.FromMinutes(stall)){State.ActivityMessage="Продвижение "+phase.ToLowerInvariant()+" не подтверждено "+(int)(DateTime.UtcNow-movement).TotalMinutes+" мин. Агент отвечает; это не доказательство зависания.";if(!diagnosed){diagnosed=true;diagnostic=Task.Run(()=>StallDiagnostic());}}else if(State.ActivityMessage.StartsWith("Продвижение"))State.ActivityMessage="";
    if(abort.HasValue&&DateTime.UtcNow-abort.Value>TimeSpan.FromSeconds(30)&&State.ForceCandidatePid>0){State.StopStatus="ForceRequired";State.StopMessage="Отмена запрошена, MRT не завершён. Доступно отдельное принудительное прерывание MRT после подтверждения.";}
    if(File.Exists(FilePath("force-stop.flag"))&&State.ForceCandidatePid>0){try{var p=Process.GetProcessById(State.ForceCandidatePid);if(MrtParentMatches(p.Id)&&p.ProcessName.Equals("MRT",StringComparison.OrdinalIgnoreCase)&&p.StartTime.ToUniversalTime().ToString("o")==State.ForceCandidateStarted){p.Kill();Log("Администратор подтвердил принудительное завершение MRT PID "+p.Id);State.ForceCandidatePid=0;State.StopMessage="MRT принудительно завершён; ожидается результат WUA, успех установки не подтверждён";Save();}}catch(Exception ex){Log("MRT не завершён: "+ex.Message);}File.Delete(FilePath("force-stop.flag"));}
    Save();Thread.Sleep(1000);
   }
   if(diagnostic!=null)diagnostic.Wait(15000);State.ActivityMessage="";
  }
  static bool MrtParentMatches(int pid){try{using(var q=new System.Management.ManagementObjectSearcher("SELECT ParentProcessId FROM Win32_Process WHERE ProcessId="+pid)){foreach(System.Management.ManagementObject row in q.Get()){int parent=Convert.ToInt32(row["ParentProcessId"]);using(var pq=new System.Management.ManagementObjectSearcher("SELECT Name,CommandLine FROM Win32_Process WHERE ProcessId="+parent)){foreach(System.Management.ManagementObject p in pq.Get())if(Convert.ToString(p["Name"]).StartsWith("Windows-KB890830",StringComparison.OrdinalIgnoreCase)&&Convert.ToString(p["CommandLine"]).IndexOf("SoftwareDistribution",StringComparison.OrdinalIgnoreCase)>=0)return true;}}}return false;}catch{return false;}}
  static void StallDiagnostic(){try{
   var candidates=Process.GetProcessesByName("MRT").Where(p=>p.StartTime.ToUniversalTime()>=DateTime.Parse(State.StageStarted).ToUniversalTime().AddSeconds(-10)).ToArray();double cpu=0;int pid=0;string started="";if(candidates.Length==1&&State.Stage.Contains("KB890830")&&MrtParentMatches(candidates[0].Id)){pid=candidates[0].Id;cpu=candidates[0].TotalProcessorTime.TotalSeconds;started=candidates[0].StartTime.ToUniversalTime().ToString("o");Thread.Sleep(15000);try{var again=Process.GetProcessById(pid);if(again.StartTime.ToUniversalTime().ToString("o")==started&&again.TotalProcessorTime.TotalSeconds==cpu){State.ForceCandidatePid=pid;State.ForceCandidateStarted=started;}}catch{}}
   string script="$ProgressPreference='SilentlyContinue';'## Диагностика долгой операции';Get-Date -Format 'dd.MM.yyyy HH:mm:ss zzz';Get-CimInstance Win32_Process -Filter \"Name='MRT.exe' OR Name='MsMpEng.exe' OR Name='TiWorker.exe'\"|Select-Object Name,ProcessId,ParentProcessId,CreationDate|Format-Table;foreach($log in @('System','Application')){Get-WinEvent -FilterHashtable @{LogName=$log;StartTime=(Get-Date).AddHours(-2);Id=7031,7034,1000,1001} -MaxEvents 100 -ErrorAction SilentlyContinue|Where-Object {$_.Message -match 'MsMpEng|Defender|Защитник'}|Select-Object -First 8 TimeCreated,Id,Message|Format-List};$p=Join-Path $env:windir 'debug\\mrt.log';if(Test-Path $p){Get-Item $p|Select-Object LastWriteTime,Length;Get-Content $p -Tail 25}";
   int code=PowerShell(script,"stall-diagnostics",90000);var path=FilePath("stall-diagnostics.out");string text=File.Exists(path)?File.ReadAllText(path):"";State.Recommendation="Откройте диагностику долгой операции; проверьте текущий установщик и доступ к источникам. Очистка кэша при установке не рекомендуется.";State.RecommendationAction="Diagnosis";
   if(text.Contains("MsMpEng.exe")&&text.Contains("c0000005"))State.Recommendation="Обнаружены падения Defender (MsMpEng.exe). Проверьте платформу Defender; связь с ожиданием установки требует проверки. Очистка кэша не рекомендована.";
   if(text.Contains("Failed to submit MAPS report"))State.Recommendation+=" MRT сообщил о тайм-ауте отправки MAPS: проверьте доступ фонового процесса к Microsoft через Kerio. Это не ошибка доставки отчёта WSUS.";if(code!=0)State.Recommendation+=" Сбор диагностики неполный.";Save();
  }catch(Exception ex){State.Recommendation="Диагностику ожидания получить не удалось: "+ex.Message;Save();}}
 }
}
