using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
namespace DomainConsole.Shared {
 public static class LogPresentation {
  static string Signature(string line){var s=Regex.Replace(line,@"^\s*\d{4}[-.]\d{2}[-.]\d{2}[ T]\d{2}:\d{2}:\d{2}(?:[.,]\d+)?(?:Z|[+-]\d{2}:\d{2})?\s*","");s=Regex.Replace(s,@"^\d+\s+\d+\s+","");return Regex.Replace(s,@"\b(?:PID|TID)=\d+\s*","").Trim();}
  public static string Compact(string text){text=Regex.Replace(text,@"(?m)^\s*(?:\d{1,3}(?:[.,]\d+)?%\s*){2,}$",m=>Regex.Matches(m.Value,@"\d{1,3}(?:[.,]\d+)?%").Cast<Match>().Last().Value);var lines=ProgressText.Compact(text).Replace("\r\n","\n").Split('\n');var result=new List<string>();for(int i=0;i<lines.Length;){if(string.IsNullOrWhiteSpace(lines[i])){if(result.Count>0&&result[result.Count-1]!="")result.Add("");i++;continue;}int end=i+1;var signature=Signature(lines[i]);while(end<lines.Length&&!string.IsNullOrWhiteSpace(lines[end])&&Signature(lines[end])==signature)end++;result.Add(lines[i]);if(end-i>2){result.Add("… пропущено одинаковых записей: "+(end-i-2)+RepeatDuration(lines[i],lines[end-1])+" …");result.Add(lines[end-1]);}else if(end-i==2)result.Add(lines[i+1]);i=end;}return string.Join(Environment.NewLine,result).TrimEnd();}
  static string RepeatDuration(string first,string last){DateTime Stamp(string line){var match=Regex.Match(line,@"^\s*(\d{4}[-.]\d{2}[-.]\d{2}[ T]\d{2}:\d{2}:\d{2})");return DateTime.TryParseExact(match.Value.Trim().Replace('.','-').Replace('T',' '),"yyyy-MM-dd HH:mm:ss",CultureInfo.InvariantCulture,DateTimeStyles.None,out var stamp)?stamp:DateTime.MinValue;}var a=Stamp(first);var b=Stamp(last);return a!=DateTime.MinValue&&b>=a?" · интервал "+(int)(b-a).TotalSeconds+" сек":"";}
  public static bool Anomaly(string line){var message=Regex.Replace(line,@"(?i)\b(?:error|failed)\s*(?:=\s*|code\s*=?\s*)?0\b","");return Regex.IsMatch(message,@"(?i)\b(?:error|failed|failure|timeout|corrupt(?:ion|ed)?)\b|ошиб|сбой|(?:0x|\[)8[0-9a-f]{7}");}
  public static string ErrorContext(string text){var lines=text.Replace("\r\n","\n").Split('\n');var keep=new SortedSet<int>();for(int i=0;i<lines.Length;i++)if(Anomaly(lines[i]))for(int j=Math.Max(0,i-2);j<=Math.Min(lines.Length-1,i+2);j++)keep.Add(j);if(keep.Count==0)return "В выбранном интервале явных ошибок не найдено; это не подтверждает успешность задания.";var output=new List<string>();int last=-2;foreach(int i in keep){if(i>last+1)output.Add("…");output.Add(lines[i]);last=i;}return Compact(string.Join("\n",output));}
  public static string LocalTimes(string text){var zoned=Regex.Replace(text,@"\b\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:[.,]\d+)?(?:Z|[+-]\d{2}:\d{2})\b",m=>DateTimeOffset.TryParse(m.Value,CultureInfo.InvariantCulture,DateTimeStyles.None,out var at)?at.ToLocalTime().ToString("dd.MM.yyyy HH:mm:ss zzz"):m.Value);return Regex.Replace(zoned,@"\b(\d{4})[-.](\d{2})[-.](\d{2})[ T](\d{2}:\d{2}:\d{2})(?:\.\d+)?",m=>m.Groups[3].Value+"."+m.Groups[2].Value+"."+m.Groups[1].Value+" "+m.Groups[4].Value).Replace("(UTC)","(местное время)");}
  public static string Duration(RemoteState state,DateTimeOffset now){DateTimeOffset start;if(!DateTimeOffset.TryParse(state.StageStarted,out start))return "";DateTimeOffset finish;bool active=state.Status=="Running"||state.Status=="Queued";if(active)finish=now;else if(!DateTimeOffset.TryParse(state.StageEnded,out finish)&&!DateTimeOffset.TryParse(state.Ended,out finish)){var last=state.Results.LastOrDefault(r=>!string.IsNullOrEmpty(r.Ended));if(last==null||!DateTimeOffset.TryParse(last.Ended,out finish))return "время завершения неизвестно";}var d=finish-start;if(d<TimeSpan.Zero)d=TimeSpan.Zero;return (int)d.TotalMinutes+" мин "+d.Seconds+" сек";}
 }
}
